FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY server.js ./

USER node
EXPOSE 3000

CMD ["node", "-r", "elastic-apm-node/start.js", "server.js"]
